### PR TITLE
RohitMidha23 - Done

### PR DESCRIPTION
**Pull request by RohitMidha23**

### CODE REVIEW

**Comment by akashsara** [comment]
Hey @RohitMidha23 

There seems to be some conflicts in your PR. Please pull all the latest changes from this master branch and resend the PR.

Additionally, please remove all `.DS_Store` files from the PR as well as the .gitignore file.

I think you will have to manually remove the `.DS_Store` files this time as they're already tracked by git. However, in the future you can ignore them by adding `**/.DS_Store` and `.DS_Store` to your `.gitignore` file. 

Modify this PR/Send a new PR once the fixes have been made and I'll be happy to merge them.

**Comment by akashsara** [comment]
Hey @RohitMidha23 

You seem to have modified the README.md file. Please restore it back to its original state by pulling the master repository. 

Also, you have saved a Jupyter notebook file  in `src/docs/`, please remove the same.

Will merge the PR once the changes are made.

**Comment by RohitMidha23** [comment]
Yeah, my bad. I think you can merge now...

**Comment by akashsara** [comment]
Awesome! Thanks for participating in A December of Algorithms. And congratulations on finishing it! I'm gonna go ahead and merge your PR. Please send an email to us at acm.svcecse@gmail.com with your full name so that we may get your certificate ready.

**Pull request merged**
