### PR TITLE
Completion

### PR DESCRIPTION
**Pull request by KumaranSS**

### CODE REVIEW

**Comment by akashsara** [comment]
Hey @KumaranSS 

The files you uploaded are all text files. You seem to have added a `.txt` extension to each file. Please update your repository with the proper code files and send the PR.

**Comment by KumaranSS** [comment]
Hey!i have made changes of that u have mentioned....

**Comment by akashsara** [comment]
Hey @KumaranSS 

You now have two versions of each file committed to your repository. In addition, both files have multiple extensions. 
https://github.com/KumaranSS/A-December-of-Algorithms/tree/master/December-01
That is a link to your local repository. Check it out to see what I mean.

Here's how to fix this issue. I think Windows has hidden file extensions in your system. Follow this guide: https://www.howtogeek.com/205086/beginner-how-to-make-windows-show-file-extensions/

Now you should be able to view file extensions. Now visit your local repository and rename your code files. Delete any extra code files and then commit to the repository.

Your final PR should have exactly 31 code files. Let me know if you need any help. :)

Make the changes and send a PR and I'll merge it.

**Comment by KumaranSS** [comment]
Ohkk I'll try to finish by today....

**Comment by KumaranSS** [comment]
I deleted my .txt files and uploaded with code files :)

**Comment by akashsara** [comment]
Hey @KumaranSS 

Thanks for participating in A December of Algorithms. And congratulations on finishing it! I'm gonna go ahead and merge your PR. Please send an email to us at acm.svcecse@gmail.com with your full name so that we may get your certificate ready.

**Pull request merged**
